version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: mon_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!2345"
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:5
    container_name: mon_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: